version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: yarn test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          - requires:
              - build
