version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn install

      # Run Jest tests
      - run:
          name: Run Tests
          command: yarn test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
